import $$ from './DOM.js'

{
  "card": ["<div class=\"contain\">",
            "<div card>",
              "<div front></div>",
              "<div back></div>",
            "</div>",
          "</div>"],
  "versus": ["<div class=\"vsContain\">",
              "<div class=\"vs\">",
                "<div></div>",
              "</div>",
              "<input type=\"button\" value=\"Play\">",
            "</div>"],
  "landing": ["<div class=\"deckLanding\"></div>",
              "<div class=\"discard\"></div>"],
  "field": ["<div playArea></div>"],
  "game": ["<div game>",
            "<div class=\"p1\">",
              "<div menu>",
                  "<select class=\"who\" blank>",
                    "<option value=\"blank\"></option>",
                    "<option value=\"Bennett0\">Bennett0</option>",
                    "<option value=\"Chris0\">Chris0</option>",
                    "<option value=\"Darwin0\">Darwin0</option>",
                    "<option value=\"Hale0\">Hale0</option>",
                    "<option value=\"Morgan0\">Morgan0</option>",
                    "<option value=\"Pearl0\">Pearl0</option>",
                  "</select>",
                  "<div class=\"select icon Empty\">",
                    "<div class=\"icon Bennett\" value=\"Bennett\"></div>",
                    "<div class=\"icon Chris\" value=\"Chris\"></div>",
                    "<div class=\"icon Darwin\" value=\"Darwin\"></div>",
                    "<div class=\"icon Hale\" value=\"Hale\"></div>",
                    "<div class=\"icon Morgan\" value=\"Morgan\"></div>",
                    "<div class=\"icon Pearl\" value=\"Pearl\"></div>",
                  "</div>",
                  "<div cdlt></div>",
              "</div>",
              "<div grid>",
              "</div>",
            "</div>",
            "<div class=\"vsContain\">",
              "<div class=\"vs\">",
                "<div></div>",
              "</div>",
              "<input type=\"button\" value=\"Play\">",
            "</div>",
            "<div class=\"p2\">",
              "<div menu>",
                  "<select class=\"who\" blank>",
                    "<option value=\"blank\"></option>",
                    "<option value=\"Bennett1\">Bennett1</option>",
                    "<option value=\"Chris1\">Chris1</option>",
                    "<option value=\"Darwin1\">Darwin1</option>",
                    "<option value=\"Hale1\">Hale1</option>",
                    "<option value=\"Morgan1\">Morgan1</option>",
                    "<option value=\"Pearl1\">Pearl1</option>",
                  "</select>",
                  "<div class=\"select icon Empty\">",
                    "<div class=\"icon Bennett\" value=\"Bennett\"></div>",
                    "<div class=\"icon Chris\" value=\"Chris\"></div>",
                    "<div class=\"icon Darwin\" value=\"Darwin\"></div>",
                    "<div class=\"icon Hale\" value=\"Hale\"></div>",
                    "<div class=\"icon Morgan\" value=\"Morgan\"></div>",
                    "<div class=\"icon Pearl\" value=\"Pearl\"></div>",
                  "</div>",
                  "<div cdlt></div>",
              "</div>",
              "<div grid>",
              "</div>",
            "</div>",
          "</div>"]
}